#!/usr/bin/env bash
set -e

echo "==> Building Nero..."
cmake -S . -B build --log-level=ERROR > /dev/null
cmake --build build --parallel > /dev/null

echo "==> Running tests..."
./build/NeroTest
ts-node -T nero_wasm_interface.test.ts

echo "==> Building..."
sh build.sh

echo "==> Updating README benchmarks..."
python3 scripts/update_bench_readme.py
git add README.md public/benchmarks.png
